#! /bin/bash


echo "Whats the name of the Project?"
read projectName
mkdir $projectName
git clone "https://github.com/LeventeBotos/clones.git" $projectName
cd $projectName
echo "Whats the accent color?"
read accent
echo "import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
       \"accent\": \"$accent\",
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
export default config
" > tailwind.config.ts
echo "NAME=\"$projectName\"" >> .env
rm -rf .git
npm i
echo "Done"